### ISSUE TITLE
Issue with uploading Videos

### ISSUE THREAD

**Issue by minhal** [coresecure/Adobe-CQ5-Brightcove-Connector#14]
Some users in the administrators group are not able to upload videos. Following is the error displayed in the log. Even though i am part of the same group i am not able to replicate this issue. 
Is there any other factor besides the allowed group property that will not allow someone to upload?

27.04.2016 10:25:24.199 _INFO_  GET /apps/mercer-brightcove/extensions/console/brightcove.proxy.json HTTP/1.1] Brightcove Command: 'search_videos'

27.04.2016 10:25:24.830 _INFO_  GET /brightcove/null HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Resource /brightcove/null not found
27.04.2016 10:25:24.832 _ERROR_ GET /brightcove/null HTTP/1.1] com.adobe.acs.commons.util.ResourceDataUtil Error creating the String representation for: /content/error.html -- {}
org.apache.sling.api.resource.ResourceNotFoundException: No resource found
        at org.apache.sling.servlets.get.impl.DefaultGetServlet.doGet(DefaultGetServlet.java:219)

**Comment by ldpaul** [comment]
We recently upgraded from CQ 5.6 to AEM 6.1.  The brightcove connector, version 4.1, does not allow us to upload videos.  We can download a video and play it just fine in the HTML 5 format.  Hence, our configuration is not the issue.  The older Brightcove software with CQ5.6 does not have this issue.

**Comment by ldpaul** [comment]
The brightcove connector has the directory path "/tmp/..." inside of /apps/brightcove/components/tools/brightcoveadmin/proxy.POST.jsp.  This was causing the failure when I was trying to upload a video using an AEM instance running under Windows.  When I installed the Brightcove connector on a AEM instance on a Unix server, everything worked fine.

**Comment by yan-kisen** [comment]
@ldpaul Do you have any suggestions for a quick fix?

**Comment by ldpaul** [comment]
I was only using the AEM instance on Windows for testing the Brightcove connector.  All our production and QA server are UNIX.  I was surprised that the Video upload was not working on Windows.  I hacked up the directory path in proxy.POST.jsp as "C:\tmp" and I was then able to upload a video.   A better solution would be to add a property to the Brightcove configuration, say "tmp_dir", and have the proxy.POST.jsp read the value from there.  Since we don't use Windows - except for testing - I'm OK with it as it is.  However, you might just put a warning in the README warning about testing the video upload from an AEM instance under Windows.
