### ISSUE TITLE
Need more info on the connector!!

### ISSUE THREAD

**Issue by AnkitSGupta** [coresecure/Adobe-CQ5-Brightcove-Connector#5]
@alessandro-bonfatti Hey wanted to know if the package is compatible with AEM 6.0 version and also what are the installation steps for using the connector?

Thanks in advance..

-Ankit Gupta

**Comment by miccor01** [comment]
Yes, this is compatible with AEM 6.0.

Regards,
Mike Cormio
Coresecure, Inc.

On Mon, Jan 26, 2015 at 6:32 PM, Ankit <notifications@github.com> wrote:

> @alessandro-bonfatti <https://github.com/alessandro-bonfatti> Hey wanted
> to know if the package is compatible with AEM 6.0 version and also what are
> the installation steps for using the connector?
>
> Thanks in advance..
>
> -Ankit Gupta
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coresecure/Adobe-CQ5-Brightcove-Connector/issues/5>.
>

-- 
*This e-mail and any files transmitted with it are property of the sender, 
intended solely for the use of the individual or entity to whom they are 
addressed and may be confidential or legally privileged or otherwise 
protected by law. If you have received this e-mail in error, you are hereby 
notified that disclosing, copying, distributing or taking any action in 
reliance on the contents of the information is strictly prohibited. Please 
notify the sender immediately by email if you have received an email by 
mistake and delete the email from your system. Email transmission cannot be 
guaranteed to be secure or error-free as information could be intercepted, 
corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. 
The sender therefore does not accept liability for any errors or omissions 
in the contents of the message, which arise as a result of email 
transmission.*

**Comment by AnkitSGupta** [comment]
I am getting just 20 videos in my Video dropdown when there must be more, any idea why it shoes only 1 page of videos which is defaulted to 20. 
Also I am not able to get videos from all the playlists, any idea what can be the problem?

**Comment by AnkitSGupta** [comment]
This is what I see in the logs ""page_number":0,"page_size":20,"total_count":340}'." but not able to see these pages in the video dialog.

**Comment by alessandro-bonfatti** [comment]
Hi Ankit, I just committed the a fix for the pagination. Let me know if it resolves your issue.

Alessandro

**Comment by AnkitSGupta** [comment]
Alessandro - I am getting many errors while trying to build the project via Maven. Is there any other way to deploy the fix files into AEM.

**Comment by AnkitSGupta** [comment]
Can the fix be merged within the package?

**Comment by yan-kisen** [comment]
This fix was deployed as of version 4.1.0
